# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_published', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
